# Generated by Django 5.0.4 on 2024-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(blank=True, max_length=255, null=True)),
                ('authToken', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
